#ifndef MINI_JIT_KERNELS_UNARY_ALL_BINARY_PRIMITIVES_H
#define MINI_JIT_KERNELS_UNARY_ALL_BINARY_PRIMITIVES_H

#include "add_primitive.h"
#include "sub_primitive.h"

#endif // MINI_JIT_KERNELS_UNARY_ALL_BINARY_PRIMITIVES_H