##
# @author Lucas Obitz, Luca-Philipp Grumbach
# @section DESCRIPTION
# Execute tests on GitHub Actions
##
name: Run Tests

on: [push, workflow_dispatch]
jobs:
  run-tests-valgrind:
    name: Run Tests (+ Valgrind)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install valgrind
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Compile Tests
        run: |
            make tests
      - name: Run Unit Tests
        run: |
            valgrind ./build/linux/tests/unit-tests
      - name: Run Integration Tests
        run: |
            valgrind ./build/linux/tests/int-tests

  run-tests-asan:
    name: Run Tests (+ ASan)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Compile Tests
        run: |
            make tests-san
      - name: Run Unit Tests
        run: |
            ./build/linux/tests/unit-tests-san
      - name: Run Integration Tests
        run: |
            ./build/linux/tests/int-tests-san